
services:
  anth2oai_server:
    image: llinkedlist/anth2oai_server:latest
    container_name: anth2oai_server
    ports:
      - "8363:8363"
    volumes:
      - .:/workspace
      - ./.env:/workspace/.env
    working_dir: /workspace
    env_file:
      - .env
    restart: always
    # entrypoint: ["python3", "-c", "import signal; signal.pause()"]
    entrypoint: ["/workspace/entrypoint.sh"]
