[project]
name = "anthropic-openai-wrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.75.0",
    "loguru>=0.7.3",
    "openai>=2.13.0",
    "python-dotenv>=1.2.1",
]
